# Generated by Django 3.0 on 2019-12-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mTitle', models.CharField(max_length=50, verbose_name='title')),
                ('mDetail', models.TextField(blank=True, verbose_name='detail')),
                ('mlink', models.CharField(max_length=100, verbose_name='link')),
                ('mimage', models.CharField(max_length=50, verbose_name='title')),
                ('mduration', models.IntegerField(verbose_name='duration')),
                ('mrating', models.FloatField(verbose_name='rating')),
                ('mlevel', models.CharField(max_length=20, verbose_name='level')),
            ],
        ),
    ]
