# Generated by Django 2.2.10 on 2020-02-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('profession', models.CharField(max_length=50, verbose_name='profession')),
            ],
        ),
    ]
