# Generated by Django 2.2.10 on 2020-02-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleproject', '0003_auto_20200204_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('mobile', models.IntegerField(verbose_name='mobile')),
                ('user_type', models.CharField(max_length=10, verbose_name='user_type')),
            ],
        ),
    ]
