# Generated by Django 2.2.10 on 2020-02-22 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('googleproject', '0005_auto_20200209_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tracking_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
